language: php

cache:
  directories:
    - $HOME/.composer/cache/files

php:
  - 5.6
  - 7.0
  - 7.1
  - hhvm

install:
  - travis_retry composer install --no-interaction

script:
  - bin/phpspec run -v --no-interaction
